import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/screens/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        main_background: "#243650",
        review_background: "#E4E4E4",
        button_background: "#B3B2B3",
        button_dark_background: "#676568",
        icon_color: "#161718",
        icon_fill_color: "#8F5231",
        action_color: "#4488ED",
        icon_back_color: "#5E718D",
        text_black: "#161718",
        text_gray: "#1C1B1B",
        border: "#C1C1C1",
        // !
        text_white: "#F0F0F0",
        black: "#161718",
        light_gray: "#C1C1C1",
        gray_our: "#9A9EA2",
        light_blue: "#D8E6FB",
        dark_blue: "#243650",
        blue_action: "#4488ED",
        blue_action_button: "#1673FF",

        button_active_page: "#DDDDDD",
        button_background_favorite: "#ffffffb3",
      },
      screens: {
        xs: "320px",
        // => @media (min-width: 320px) { ... }

        sm: "480px",
        // => @media (min-width: 480px) { ... }

        md: "768px",
        // => @media (min-width: 768px) { ... }

        lg: "1440px",
        // => @media (min-width: 1280px) { ... }
      },
      margin: {
        describe_big: "80px",
        describe_big_after_title: "32px",
        describe: "32px",
        describe_after_title: "32px",
      },
      fontFamily: {
        roboto: [`var(--font-roboto)`],
        inter: [`var(--font-inter)`],
        robotoSerif: [`var(--font-roboto_serif)`],
      },
      fontSize: {
        size_14: "14px",
        size_16: "16px",
        size_18: "18px",
        size_20: "20px",
        size_22: "22px",
        size_32: "32px",

        title_section: "32px",
        title_filter: "20px",
        text_filter: "18px",
        text_description: "16px",
        text_description_home: "18px",
        type_add_info: "20px",
        text_footer: "16px",
        title_footer: "16px",
        button_footer: "20px",
        review_content: "18px",
        review_text: "14px",
        review_title: "18px",
        button_add_review: "20px",
        text_add_info: "18px",
        text_header: "20px",
        text_header_logo: "32px",
        text_sum_order: "20px",
        title_product: "20px",
        title_checkout: "22px",
        title_second: "16px",
        text_user_info: "14px",
      },
      fontWeight: {
        weight_300: "300",
        weight_400: "400",
        weight_500: "500",
        weight_600: "600",

        title_section: "400",
        title_filter: "600",
        text_filter: "400",
        text_description: "400",
        text_description_home: "400",
        type_add_info: "300",
        text_footer: "300",
        title_footer: "600",
        button_footer: "400",
        review_content: "300",
        review_text: "300",
        review_title: "500",
        button_add_review: "300",
        text_add_info: "300",
        text_header: "400",
        text_header_logo: "400",
        text_sum_order: "500",
        title_product: "400",
        title_checkout: "600",
        title_second: "500",
        text_user_info: "500",
      },
      lineHeight: {
        line_height_15: "1.15",
        line_height_16: "1.16",
        line_height_17: "1.17",
        line_height_20: "1.2",
        line_height_22: "1.22",
        line_height_28: "1.28",
        line_height_29: "1.29",
        line_height_31: "1.31",
        line_height_50: "1.5",
        line_height_60: "1.6",
        line_height_71: "1.71",
        line_height_75: "1.75",

        title_section: "1.16",
        title_filter: "1.2",
        text_filter: "1.22",
        text_description: "1.31",
        text_description_home: "1.28",
        type_add_info: "1.2",
        text_footer: "1.5",
        title_footer: "1.5",
        button_footer: "1.6",
        review_content: "1.28",
        review_text: "1.29",
        review_title: "1.28",
        button_add_review: "1.15",
        text_add_info: "1.17",
        text_header: "1.2",
        text_header_logo: "1.22",
        text_sum_order: "1.15",
        title_product: "1.17",
        title_checkout: "1.6",
        title_second: "1.75",
        text_user_info: "1.71",
      },
    },
  },
  plugins: [],
};
export default config;
